###### The cell below loads the visual style of the notebook when run.

In [4]:
#from IPython.core.display import HTML
#css_file = '../../styles/styles.css'
#HTML(open(css_file, "r").read())

# Introducing Numpy

<section class="objectives panel panel-warning">
<div class="panel-heading">
<h2><span class="fa fa-certificate"></span>Learning Objectives</h2>
</div>
</section>

> * How to import libraries, and where to find useful libraries. 
> * Explain why numpy is more useful than Python lists
> * Use numpy for simple operations on arrays.
> * Learn how to slice numpy arrays
> * Read tabular data from a file into a program.

---

<section class="objectives panel panel-warning">
<div class="panel-heading">
<h2><span class="fa fa-check"></span>Prerequisites</h2>
</div>
</section>

> Before starting this lecture, it is assumed you are familiar with
> material in part 2 of the Python Bootcamp

---

## Numpy

As a reminder, most of Python's functionatility comes from the use of [libraries](../../resources/reference.html#library). `numpy` is one such library that is designed to work with arrays of data, which are useful to represent vectors and matrices. `numpy` also provides routines to perform operations on the whole array in one line of code. We often import numpy using an alias to save typing:

In [1]:
import numpy as np

The core of numpy is the `array` object. We'll start by looking at how numpy's arrays differ from a Python `list`. We can create a numpy array from a Python list like so:

In [3]:
a_list = [1,2,3,4] # a python list
an_array = np.array( a_list ) # one way to make an array
an_array = np.array( [1,2,3,4] ) # another way

print(an_array)

[1 2 3 4]


We saw in the [bootcamp](http://nbviewer.ipython.org/github/StuartLittlefair/python-teaching/blob/master/pybootcamp-part2/01-numpy.ipynb) how to access elements of a numpy array or a Python list:

In [4]:
print (a_list[0])
print (an_array[0])

1
1


In [5]:
print (a_list[1:3])
print (an_array[1:3])

[2, 3]
[2 3]


## Differences between arrays and lists
---

What's the difference? To start with, Python's lists are very flexible and can contain different [types](../../resources/reference.html#type) of objects:

In [6]:
a_list[-1] = 'a string inside a list'
print(a_list)

[1, 2, 3, 'a string inside a list']


whereas numpy arrays can only contain a single type!

In [7]:
an_array[-1] = 'a string inside an array'

ValueError: invalid literal for int() with base 10: 'a string inside an array'

Information about the type of object in a numpy array is stored in the `dtype` [member](../../resources/reference.html#member)

In [8]:
an_array.dtype

dtype('int64')

Once the array is created, the `dtype` is fixed, and an array can only hold that type. For example, if we try and put a [floating point number](../../resources/reference.html#floating-point-number) in our array, it gets converted to an [integer](../../resources/reference.html#integer):

In [9]:
an_array[-1] = 1.3141
print(an_array)

[1 2 3 1]


## Why use arrays?
---

Right now, numpy arrays look less useful than Python lists! 

But numpy arrays are fast, and smart. Numpy has [methods](../../resources/reference.html#method) which allow fast computations on all elements of the array at the same time, and some other tricks up it's sleeve that we'll look at later.

As a taster, let's compare two ways of calculating the sum of all the elements in a list or array. Make sure each function makes some sense to you before running the code.

In [10]:
def sum_python(a_list):
    '''Add up all the values in a list or array using plain Python'''
    sum = 0.0
    for thing in a_list:
        sum += thing
    return sum

def sum_numpy(a_list):
    '''Add up all the values in a list or array using numpy'''
    return np.sum(a_list)

In [11]:
my_list = np.random.randn(1000) # use numpy to create an array of 1000 random numbers
%timeit sum_python(my_list)

125 μs ± 32.9 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [12]:
%timeit sum_numpy(my_list)

The slowest run took 11.55 times longer than the fastest. This could mean that an intermediate result is being cached.
16.9 μs ± 23.3 μs per loop (mean ± std. dev. of 7 runs, 1 loop each)


We can see that using numpy allows us to avoid ```for``` loops, and so leads to simpler code, but also that the numpy code is around 40 times faster!

<section class="challenge panel panel-success"> 
<div class="panel-heading">
<h2><span class="fa fa-pencil"></span>Numpy vs List</h2>
</div>
</section>

> Write two functions to calculate the mean of a list/array of numbers; one should use pure Python and the other should use numpy. Compare your answer to your neighbour. Are your answers similar? Which did you find easier to write?

> Hint: the mean of a list of numbers is the sum of all the numbers, divided by the size of the list, so use the functions above as a template.

In [13]:
def mean_python(my_list):
    """Calculate the mean of an input list of numbers"""
    sum = 0.0
    for thing in my_list:
        sum += thing
    return sum / len(my_list)
    #list_length = len(my_list)
    #print(list_length)
    #mean = sum/list_length
    #return mean

def mean_numpy(my_list):
    """Calculate the mean of a numpy array"""
    return np.mean(my_list)

In [14]:
my_list2 = [1,2,3,4,5,6,7,8]

In [15]:
mean_python(my_list2)

4.5

In [16]:
mean_numpy(my_list2)

np.float64(4.5)

## Creating arrays
---

We have seen that we can create arrays from lists. Let's look at a few more ways of creating arrays. We can create arrays filled with zeros or ones:

In [31]:
zeros = np.zeros(5)
ones  = np.ones(3)

print(zeros)
print(ones)

[0. 0. 0. 0. 0.]
[1. 1. 1.]


Numpy also offers the `arange` function which returns an array of evenly spaced values: 

In [32]:
np.arange(0, 5, 1) # min, max(exclusive), step

array([0, 1, 2, 3, 4])

and the very useful `linspace` function to create a linearly-spaced grid, with a fixed number of points and including both ends of the specified interval: 

In [33]:
print ("A linear grid of 5 points between 0 and 2:")
print (np.linspace(0, 2, 5)) #min, max (inclusive), num_points

A linear grid of 5 points between 0 and 2:
[0.  0.5 1.  1.5 2. ]


## Arrays with more than one dimension
---

We've used 1D numpy arrays so far, but all the methods discussed work with arrays with 2 or more dimensions, e.g:

In [34]:
np.zeros( (2,2) )

array([[0., 0.],
       [0., 0.]])

In [35]:
x = np.random.normal(loc=5, scale=2, size=(5,4))
print(x)

[[ 2.87396939  5.73248066  8.32559909  6.4316906 ]
 [ 0.87014814 10.19754543  8.21591105  3.86642208]
 [ 7.06866939  7.42023883  5.24589837  2.95467898]
 [ 9.5588468   5.78065269  3.79946093  5.14276129]
 [ 2.82446322  5.79167661  4.86168641  4.55509317]]


You can create a 2D array from a list of lists:

In [36]:
list_of_lists = [ [1,2,3], [4,5,6], [7,8,9] ] # each list is a row
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Arrays can even have their shape changed, as long as we don't change the total number of elements in the array:



In [37]:
x.reshape((10,2))

array([[ 2.87396939,  5.73248066],
       [ 8.32559909,  6.4316906 ],
       [ 0.87014814, 10.19754543],
       [ 8.21591105,  3.86642208],
       [ 7.06866939,  7.42023883],
       [ 5.24589837,  2.95467898],
       [ 9.5588468 ,  5.78065269],
       [ 3.79946093,  5.14276129],
       [ 2.82446322,  5.79167661],
       [ 4.86168641,  4.55509317]])

<section class="challenge panel panel-success"> 
<div class="panel-heading">
<h2><span class="fa fa-pencil"></span>Views, not copies</h2>
</div>
</section>

> Reshaping an array, like most numpy operations, provides a **view** of the *same bit* of computer memory. Without running it, what do you expect the code below to print? 

> ``` python
> arr  = np.arange(8)
> arr2 = arr.reshape(2, 4)
> 
> arr[0] = 1000
> print (arr)
> print (arr2)
> ```

> Now run the code below. Did you get what you expected?



In [30]:
arr  = np.arange(8)
arr2 = arr.reshape(2, 4)

arr[0] = 1000
print (arr)
print (arr2)

[1000    1    2    3    4    5    6    7]
[[1000    1    2    3]
 [   4    5    6    7]]


> This lack of copying might be confusing at times, but it makes numpy very efficient and fast.

## Array methods and properties
---

One of the great things about numpy arrays is the many [methods](../../resources/reference.html#methods) that allow us to quickly get info about an array, or perform some operation on it. Here are some useful ones:

In [39]:
print ('Data type                :', arr2.dtype)
print ('Total number of elements :', arr2.size)
print ('Number of dimensions     :', arr2.ndim)
print ('Shape (dimensionality)   :', arr2.shape)

Data type                : int64
Total number of elements : 8
Number of dimensions     : 2
Shape (dimensionality)   : (2, 4)


In [40]:
print ('Minimum and maximum             :', arr.min(), arr.max() )
print ('Mean and standard deviation     :', arr.mean(), arr.std() )

Minimum and maximum             : 1 1000
Mean and standard deviation     : 128.5 329.4013509383348


<section class="challenge panel panel-success"> 
<div class="panel-heading">
<h2><span class="fa fa-pencil"></span>Array methods</h2>
</div>
</section>

> Use the <kbd>Tab</kbd> completion feature of the Jupyter notebook to browse through all the methods belonging to the `arr2` object. Use the `argmax` method to find the index and value of the largest value in `arr2`

In [31]:
print(arr2)

arr2_max = np.max(arr2)
arr2_min = np.min(arr2)
arr2_argmax = np.argmax(arr2)
arr2_argmin = np.argmin(arr2)

print(f"Largest value in arr2: {arr2_max}" )
print(f"Smallest value in arr2: {arr2_min}")
print(f"Index of largest value in arr2: {arr2_argmax}")
print(f"Index of smallest value in arr2: {arr2_argmin}")

[[1000    1    2    3]
 [   4    5    6    7]]
Largest value in arr2: 1000
Smallest value in arr2: 1
Index of largest value in arr2: 0
Index of smallest value in arr2: 1


## Array Operations
---

Arrays support all the normal math operators (+, -, / etc). The numpy library also contains a complete collection of basic mathematical functions that operate on arrays. In general, the math operators act on **every element of an array in turn**. Again, this means you don't have to use for loops to add all the numbers in two arrays together. For example:

In [46]:
arr1 = np.arange(4)
arr2 = np.arange(10, 14)
print (arr1, '+', arr2, '=', arr1+arr2)

[0 1 2 3] + [10 11 12 13] = [10 12 14 16]


In particular, multiplication is **not** matrix multiplication, but multiplies each element of the arrays together in turn:

In [47]:
print (arr1, '*', arr2, '=', arr1*arr2)

[0 1 2 3] * [10 11 12 13] = [ 0 11 24 39]


We can also multiply arrays by scalars:

In [48]:
print (arr1 * 3)

[0 3 6 9]


This is a first example of *broadcasting*.

In principle, to add two arrays their shapes must match. However, numpy will *broadcast* the shapes to match if possible. Broadcasting is a bit beyond the level of this course, but if you find yourself needing to understand it, it is described in the companion notebook ```01a-broadcasting.ipynb```.

As we mentioned before, numpy ships with many mathematical functions that work on entire arrays, including logarithms, exponentials, and trigonometric functions. For example, calculating the sine function at 100 points between $0$ and $2\pi$ is as simple as: 

In [49]:
x = np.linspace(0.0,2.0*np.pi,100)
y = np.sin(x)

Using Numpy to do calculations on lots of values at once is a great way to *speed up your code* and make it *simpler to understand*. If you ever find yourself looping over an array to do some calculation with each element in turn, stop, and see if Numpy can do the hard work for you.

### Linear Algebra in numpy

numpy has a `dot` method which gives the dot product between two vectors (one-dimensional arrays), or matrix multiplication when one or both of its arguments are matrices (two-dimensional arrays): 

In [50]:
v1 = np.array([2, 3, 4])
v2 = np.array([1, 0, 1])
result = np.dot(v1,v2)

print (v1, '.', v2, '=', result)

[2 3 4] . [1 0 1] = 6


Here is a regular matrix-vector multiplication, note that the array `v1` should be viewed as a column vector in traditional linear algebra notation

In [51]:
A = np.arange(6).reshape(2, 3)
result = np.dot(A, v1)

print (A, 'x', v1, '=', result)

[[0 1 2]
 [3 4 5]] x [2 3 4] = [11 38]


We can calculate transposes of arrays with `arr.T`, and `np.linalg` module contains methods to find eigenvectors, determinants and much more.

<section class="challenge panel panel-success"> 
<div class="panel-heading">
<h2><span class="fa fa-pencil"></span>Numpy Maths Challenge</h2>
</div>
</section>

> A system of linear equations can be written in matrix form.
>
> $$3x + 6y - 5z = 12$$
> $$x - 3y + 2z  = -2$$
> $$5x - y + 4z  = 10$$
>
> $$\left[\begin{matrix} 3 & 6 & -5 \\ 1 & -3 & 2 \\ 5 & -1 & 4 \end{matrix}\right]
 \left[\begin{matrix} x \\ y \\ z \end{matrix}\right] = \left[\begin{matrix} 12 \\ -2\\ 10 \end{matrix}\right]$$
>
> Now, representing the matrix system as $\mathbf{AX} = \mathbf{B}$, we can see the solution is given by $\mathbf{X} = \mathbf{A^{-1}B}$. 
>
> Write some numpy code to find the solution of these equations.
>
> Hint: `np.linalg.inv` can be used to find a matrices inverse...

In [17]:
A = np.array(
    [[3, 6, 5],
     [1, -3, 2],
     [5, -1, 4]])

B = np.array([12, -2, 10])

A_inv = np.linalg.inv(A)
#X = A_inv * B
X = np.dot(A_inv, B)
print(X)

#x = np.sum(X[0])
#y = np.sum(X[1])
#z = np.sum(X[2])

print()

print("x = ", x)
print("y = ", y)
print("z = ", z)

[ 2.73684211  1.15789474 -0.63157895]

x =  2.7368421052631584
y =  1.157894736842105
z =  -0.6315789473684212


## NumPy slicing

---

[Slicing](../../resources/reference.html#slice) is the term used to refer to extracting part of an array. We already saw some basic slicing in the [bootcamp](http://nbviewer.ipython.org/github/StuartLittlefair/python-teaching/blob/master/pybootcamp-part2/01-numpy.ipynb). As a quick reminder, we use the syntax `arr[lower:upper:step]` like so:



In [33]:
A = np.array([1,2,3,4,5,6,7,8])
A[1:6:2]

array([2, 4, 6])

We can omit any part of the `[lower:upper:step]` notation:

In [99]:
print (A[2:]) #from index 2 to the end, assumed step=1
print (A[:3]) # from index 0 to 3
print (A[::2]) # from 0 until the end, in steps of 2

[3 4 5 6 7 8]
[1 2 3]
[1 3 5 7]


And slicing works the same way for arrays with more dimensions:

In [100]:
B = np.arange(36).reshape((6,6))
print (B)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [101]:
print (B[1:3]) # just rows 2 and 3

[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [102]:
print (B[1:3, 1:3]) # columns 1-3 and rows 1-3

[[ 7  8]
 [13 14]]


In [103]:
print (B[1, :])  # row 1, all columns

[ 6  7  8  9 10 11]


In [104]:
print (B[:, 0])  # column 0 (the first column), and all rows

[ 0  6 12 18 24 30]


### Fancy slicing

We can use numpy arrays or python lists to slice numpy arrays as well! This is an extremely powerful technique.

In [105]:
row_indices = [1, 3, 5]
print (B[row_indices])

[[ 6  7  8  9 10 11]
 [18 19 20 21 22 23]
 [30 31 32 33 34 35]]


Why is this so useful? We can also use arrays of `True` and `False` values, known as *masks* as an index. If the mask is `True`, the element will be selected. For example, we can calculate a mask to see if each element of B is odd:

In [106]:
is_odd = (B % 2 != 0) # does each element of B divide by two with no remainder?
print (is_odd)

[[False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]]


And use that mask to select only the odd values:

In [107]:
print(B[is_odd] )

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35]


You can negate a mask (switch True and False) with `~`, so to find the even numbers we use:

In [110]:
print( B[~is_odd] )

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34]


<section class="challenge panel panel-success"> 
<div class="panel-heading">
<h2><span class="fa fa-pencil"></span>Fancy slicing</h2>
</div>
</section>

> Use `np.arange` to make a 1D array of values from 0 to 100 (inclusive) and calculate the sum of only the even values using fancy slicing. Compare your answer to your neighbour. Do you get the same answer? Is your code the same?

In [56]:
G = np.arange(0,101)
is_even = (G % 2 == 0)
G_sum = (G[is_even])
even_sum = np.sum(G_sum)
print(even_sum)

2550


## Reading and writing data to files
---

It is perfectly possible to read and write files without using numpy. Files are opened using the `open` function. This returns a [file object](../../resources/reference.html#file-object) which is used to read or write the file. It is most often used with two arguments

```python
file_handle = open(filename,mode)
```

The second argument is a string containing a few characters describing the way in which the file will be used. mode can be `r` when the file will only be read, `w` for only writing (an existing file with the same name will be erased), and `a` opens the file for appending; any data written to the file is automatically added to the end. The mode argument is optional, if it is missing, `r` is assumed.

For example, I have a file with some basic data on temperature in Stockholm. Below I show how you would open a file and read in the lines in pure Python. Notice how the ```open``` function gets what we call a *relative path* for the file; this is how to get to the file from the location of the notebook on the filesystem. The symbol ".." means "go up one directory".

In [135]:
file_handle = open('../../data/Session1/td_stockholm.dat','r') # open file for reading
lines = file_handle.readlines() # read in all the lines into a list
for line in lines[0:5]: # iterate over the first few lines
    print(line) # print out line

file_handle.close()

#year month day min   temperature   max flag

1800  1  1    -6.1    -6.1    -6.1 1

1800  1  2   -15.4   -15.4   -15.4 1

1800  1  3   -15.0   -15.0   -15.0 1

1800  1  4   -19.3   -19.3   -19.3 1



You can see this is a space separated text file. If we wanted to convert this data to a numpy array we can imagine writing the code to do so. It would:

* read in the lines into a list
* for each line in the list
 * skip header lines if necessary
 * split lines into fields at the whitespace
 * put the fields into a numpy array
 
This code is obviously going to be very similar for each file and it would make sense to write  a function you could re-use. But the first lesson of Python club is to see if someone else has done it for you! In this case they have, and we can look at `np.loadtxt`:

In [3]:
#np.loadtxt?

Looking at the help for this function, we can see that we can read in the file above with:

In [125]:
data = np.loadtxt('../../data/Session1/td_stockholm.dat', skiprows=1)
print(data.shape)

(77431, 7)


We've got our 7 columns and 77431 rows. We can use slicing to access individual columns:

In [126]:
year = data[:, 0] # first column
month = data[:, 1]
day = data[:, 2]
temperature = data[:, 5]
# calculate a 'decimal year' for each observation
# NOTICE HOW NUMPY ALLOWS US TO CALCULATE EVERY ROW IN ONE LINE.
obs_time = year + month/12 + day/31

And plot the data (plotting is discussed in another lecture):

In [127]:
%matplotlib inline
import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(14,4))
ax.plot(obs_time,temperature)
ax.axis('tight')
ax.set_title('tempeatures in Stockholm')
ax.set_xlabel('year')
ax.set_ylabel('tempature (C)');

## Writing files
---

Suppose we want to save our data to a file? `np.savetxt` will take a 2D numpy array and save it to a simple text file. We can stack our 1D columns into a 2D array with `np.column_stack`:

In [129]:
data_out = np.column_stack([obs_time, temperature])

And we can save this 2D array to a comma-seperated value file with `np.savetxt`:

In [130]:
np.savetxt('output.csv', data_out, delimiter=',')

In [131]:
!head output.csv

1.800115591397849357e+03,-6.099999999999999645e+00
1.800147849462365457e+03,-1.540000000000000036e+01
1.800180107526881557e+03,-1.500000000000000000e+01
1.800212365591397884e+03,-1.930000000000000071e+01
1.800244623655913983e+03,-1.680000000000000071e+01
1.800276881720430083e+03,-1.140000000000000036e+01
1.800309139784946183e+03,-7.599999999999999645e+00
1.800341397849462282e+03,-7.099999999999999645e+00
1.800373655913978382e+03,-1.009999999999999964e+01
1.800405913978494482e+03,-9.500000000000000000e+00


<section class="challenge panel panel-success"> 
<div class="panel-heading">
<h2><span class="fa fa-pencil"></span>File IO</h2>
</div>
</section>

> Read the help file for `np.loadtxt` and try and read only the minimum and maximum
> temperature from the file. Place the data *directly* in two numpy arrays. Your call
> should start like
> ```python
> temp_min, temp_max = np.loadtxt(...
> ```
> Save the min and max temp to a new file in a format of your choice using `np.savetxt`



In [135]:
data = np.loadtxt('../../data/Session1/td_stockholm.dat', skiprows=1)
temperature = data[:, 5]
temp_min = temperature.min()
temp_max = temperature.max()
data_out = np.column_stack([temp_min, temp_max])
np.savetxt('test.csv', data_out, delimiter=',')
!head test.csv

-2.580000000000000071e+01,2.750000000000000000e+01


---------
<section class="challenge panel panel-success"> 
<div class="panel-heading">
<h1>Homework #1</h1>
<h2><span class="fa fa-pencil"></span>Advanced File IO and Slicing</h2>
</div>
</section>

> In the data directory is a file named 'sdss_wds.csv'. This is a comma-seperated values file of data about white dwarfs discovered in the Sloan Digital Sky Survey. Your job is to investigate how the median mass of the white dwarfs depends on temperature.

>The code below prints out the first few lines of the file. As you can see, there is one header row which tells us what the columns are.

In [57]:
lines = open('../../data/Session1/sdss_wds.csv', 'r').readlines()
for line in lines[0:4]:
    print (line)

RAJ2000,DEJ2000,umag,gmag,Teff,Mass

0.028139, -0.7816610, 19.17, 18.83, 10772, 0.824

0.029825, -9.7277340, 19.41, 19.58, 29354, 0.477

0.051353, -0.8451580, 20.41, 20.04, 7994, 0.794



<section class="challenge panel panel-success"> 
<div class="panel-heading">
<h2><span class="fa fa-question"></span> Question 1 (1 points)</h2>
</div>
</section> 

> Look at the documentation for `np.loadtxt` and work out how to read in the file above. 

> Use `np.loadtxt` to load the white dwarf file into an array called `data`.

> **If you are successful, your code will pass the tests below each question. You can also use these tests to see if your code gives the right answer.**

In [20]:
data = np.loadtxt("../../data/Session1/sdss_wds.csv", delimiter=",", dtype=str, skiprows=1)
print(data[0:5])

[['0.028139' ' -0.7816610' ' 19.17' ' 18.83' ' 10772' ' 0.824']
 ['0.029825' ' -9.7277340' ' 19.41' ' 19.58' ' 29354' ' 0.477']
 ['0.051353' ' -0.8451580' ' 20.41' ' 20.04' ' 7994' ' 0.794']
 ['0.093897' ' -10.8617160' ' 19.29' ' 18.91' ' 8598' ' 0.789']
 ['0.095315' ' -0.1099130' ' 18.24' ' 18.21' ' 22222' ' 0.415']]


In [21]:
from nose.tools import assert_tuple_equal, assert_false, assert_true  
assert_tuple_equal(data.shape, (13673, 6))

<section class="challenge panel panel-success"> 
<div class="panel-heading">
<h2><span class="fa fa-question"></span>Question 2 (4 points)</h2>
</div>
</section> 

> `np.loadtxt` has read in our text files, and we have placed the contents into a 2D array called "data". Complete the function outline below to create a function which will take this 2D array and return a user-specified column. The function should return a 1D array of the column values.

> Get into the habit of reading the documentation at the start of the function to understand how it should work, and what the function [arguments](../../resources/reference.html#argument) should be.

> Use [defensive programming](../../resources/reference.html#defensive-programming) and assert statements to make sure that the function only accepts valid column numbers.

> Again, try and get your code to pass the tests that I have written in the cells below.

In [22]:
def get_column(data, col_num):
    """Filter a numpy array and return the requested column.

    Given a 2D numpy array, and a column number, this function returns the 
    requested column number as a 1D numpy array.

    Args:
        data (numpy.ndarray): the array to filter
        col_num (int): the column number to return (e.g `0` for the first column in the array).
    """
    # here's an example of using defensive programming to make sure data is a 2D array
    # notice how we run these checks before doing anything else
    assert(len(data.shape) == 2), "data must be 2D array"
    
    max_columns = len(data[1])
    assert(col_num < max_columns), f"Data doesn't have a {col_num}th column"
    assert(col_num >= 0), f"Column number cannot be negative"    
    test = np.array(data[:,col_num], dtype=float).reshape(len(data),1)
    
    print(test.shape)
    return test

get_column(data,5)

(13673, 1)


array([[0.824],
       [0.477],
       [0.794],
       ...,
       [0.748],
       [0.559],
       [0.559]])

In [23]:
from nose.tools import assert_equal, assert_almost_equal
teff = get_column(data, 4)
mass = get_column(data, 5)
assert_equal(len(teff), 13673)
assert_equal(len(mass), 13673)
assert_almost_equal(teff.mean(), 17103.082278943904)

(13673, 1)
(13673, 1)


In [24]:
from nose.tools import assert_raises
assert_raises(AssertionError, get_column, data, -1 )
assert_raises(AssertionError, get_column, data, 6 )

<section class="challenge panel panel-success"> 
<div class="panel-heading">
<h2><span class="fa fa-question"></span>Question 3 (1 points)</h2>
</div>
</section>

> What is the median mass of the white dwarfs found in the Sloan Digital Sky Survey? Store your answer in a variable named `median_mass`. Store the mean mass in a variable named `mean_mass`

In [25]:
median_mass = np.median(get_column(data,5))
mean_mass = np.mean(get_column(data,5))
print(f"Median mass: {median_mass}, Mean mass: {mean_mass}")

(13673, 1)
(13673, 1)
Median mass: 0.594, Mean mass: 0.6216425802676809


In [26]:
from nose.tools import assert_almost_equal
assert_almost_equal(median_mass, 0.5939999999999999)
assert_almost_equal(mean_mass, 0.62164258026768093)

<section class="challenge panel panel-success"> 
<div class="panel-heading">
<h2><span class="fa fa-question"></span>Question 4 (2 points)</h2>
</div>
</section>

> Why do the mean and median masses differ? What does this tell you about the *shape* of the mass distribution of white dwarfs discovered in the Sloan Digital Sky Survey?

The mean mass being larger than the median mass could show the mass data is positively skewed due to more values in the dataset having large values, having more large values in the dataset increases the mean due to a larger difference between the maximum and minimum values in the dataset.


<section class="challenge panel panel-success"> 
<div class="panel-heading">
<h2><span class="fa fa-question"></span>Question 5 (2 points)</h2>
</div>
</section>

> Use fancy slicing to find the mean mass of white dwarfs cooler than 12,000K. Store your answer in the variable ```mean_mass_coolwd```.



In [27]:
Temp = get_column(data,4)
Mass = get_column(data,5)
Temp_Mass = np.hstack((Temp, Mass))

#print(Temp_Mass.shape)
#print(Temp_Mass[0:10])
Temp_value = 12000

condition_cool = (Temp_Mass[:,0] < Temp_value)
Temp_Mass_Condition_cool = (Temp_Mass[condition_cool])
print(len(Temp_Mass_Condition_cool))

max_temp_cool = Temp_Mass_Condition_cool[:,0].max()
assert(max_temp_cool < Temp_value), f"Data set has values of Temperature above {Temp_value}K"

mean_mass_coolwd = np.mean(Temp_Mass_Condition_cool[:,1])
STD_coolwd = np.std(Temp_Mass_Condition_cool)
print(f"Mean mass of white dwarfs cooler than {Temp_value}K: {mean_mass_coolwd}")
print(STD_coolwd)

(13673, 1)
(13673, 1)
4473
Mean mass of white dwarfs cooler than 12000K: 0.671780460541024
4757.219166538474


In [121]:
from nose.tools import assert_almost_equal
assert_almost_equal(mean_mass_coolwd, 0.67178046054102403)

<section class="panel panel-warning"> 
<div class="panel-heading">
<h2><span class="fa fa-question"></span>Extra Credit (2 points)</h2>
</div>
</section>

> Extra credit questions allow you to make up for marks dropped in this and other homeworks. You can't score more than 100% overall, but if you get 2 extra credit points this week, and lose 2 points next week, you'd still be on course for 100% marks. I don't expect you to answer extra credit questions, *unless you want to*.

> For extra credit this week, use the techniques you've learned above and your own statistical knowledge to justify whether the cool white dwarfs are *significantly* different in mass to the hotter white dwarfs. Use the code cell to make any calculations you need, and the markdown cell to justify your answer.

In [119]:
Temp = get_column(data,4)
Mass = get_column(data,5)
Temp_Mass = np.hstack((Temp, Mass))

Temp_value = 12000
condition_hot = (Temp_Mass[:,0] > Temp_value)
Temp_Mass_Condition_hot = (Temp_Mass[condition_hot])
print(len(Temp_Mass_Condition_hot))

min_temp_hot = Temp_Mass_Condition_hot[:,0].min()
assert(min_temp_hot > Temp_value), f"Data set has values of Temperature below {Temp_value}K"

mean_mass_hotwd = np.mean(Temp_Mass_Condition_cool[:,1])
STD_hotwd = np.std(Temp_Mass_Condition_hot)
print(f"Mean mass of white dwarfs hotter than {Temp_value}K: {mean_mass_hotwd}")
print(STD_hotwd)

(13673, 1)
(13673, 1)
9196
Mean mass of white dwarfs hotter than 12000K: 0.671780460541024
12690.386455857135


### The mean mass of both cool and hot white dwarfs are very close values \(showing that both datasets centre around the same point\), however the standard deviation of hot white dwarfs is vastly larger than the standard deviation of cool white dwarfs. This shows that the mass of hot white dwarfs varies a lot more from its mean than cool white dwarfs therefore the mass distribution of cool white dwarfs is significantly different than hot white dwarfs

