###### The cell below loads the visual style of the notebook when run.


In [4]:
from IPython.core.display import HTML
css_file = '../../styles/styles.css'
HTML(open(css_file, "r").read())

# Numpy Broadcasting

In principle, the dimensions of two arrays must match for them to be added, subtracted etc. Numpy has [broadcasting](../../resources/reference.html#broadcast) rules to deal with a view special cases where this is not true.

We can broadcast a scalar to a 1D array:

In [5]:
import numpy as np
x = np.linspace(0,10,11)
x+3

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.])

We can also broadcast a 1D array to a 2D array, in this case adding a vector to all rows of a matrix:

In [6]:
A = np.ones((3,3))
B = np.arange(3)

print(A)
print (B)
np.ones((3, 3)) + np.arange(3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]


array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

## The Rules

Broadcasting rules can do the following:

1. If the two arrays differ in their number of dimensions, the shape of the array with fewer dimensions is padded with ones on its leading (left) side.
1. If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
1. If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

The diagram below shows these rules in visual form

<img src="../../images/fig_broadcast_visual_1.png"/>
<div style="text-align: center;"><a href="http://www.astroml.org/book_figures/appendix/fig_broadcast_visual.html">Source of figure</a></div>

<section class="challenge panel panel-success"> 
<div class="panel-heading">
<h2><span class="fa fa-pencil"></span>Check your understanding</h2>
</div>
</section>

> Will the following examples work? Run them and see if you were correct

> ```python
> arr1 = np.ones((2, 3))
> arr2 = np.ones((2, 1))
> arr1 + arr2
> ```

> ```python
> arr1 = np.ones((2,3))
> arr2 = np.ones(2)
> arr1 + arr2
> ```

In [9]:
arr1 = np.ones((2,3))
arr2 = np.ones(2).reshape(2,1)
arr1 + arr2

array([[2., 2., 2.],
       [2., 2., 2.]])

> Now look at the image below. Does this help you understand the examples above?
> <img src="../../images/fig_broadcast_visual_2.png"/>

<section class="challenge panel panel-success"> 
<div class="panel-heading">
<h2><span class="fa fa-pencil"></span>Broadcasting challenge</h2>
</div>
</section>

> Use `np.arange` and `reshape` to create the array
>
> ```python
> A = [[1 2 3 4]
>      [5 6 7 8]]
> ```
>
> and `np.arange` to create the array
>
> ```python
> B = [3 4]
> ```
>
> Use broadcasting to produce
> 
> ```python
> A + B = [[4  5  6  7]
>          [9 10 11 12]]
> ```

> Hint: What shape does `B` need to be?

In [15]:
A = np.arange(1,9).reshape(2,4)
print(A)

B = np.arange(3,5).reshape(2,1)
print(B)

A + B

[[1 2 3 4]
 [5 6 7 8]]
[[3]
 [4]]


array([[ 4,  5,  6,  7],
       [ 9, 10, 11, 12]])

Another way to change the shape of B is to use the `newaxis` keyword: 

In [0]:
B = np.arange(1, 3)
print (B.shape)
print (B.reshape((2,1)).shape)
print (B[:,np.newaxis].shape)